select producto.nombre from producto;
select producto.nombre, producto.precio from producto;
select* from producto;
select producto.nombre, producto.precio, precio*1.10 from producto;
select producto.nombre as producto, producto.precio as €, precio*1.10 as usd from producto;
select upper(producto.nombre) as mayus, producto.precio from producto;
select lower(producto.nombre) as minus, producto.precio from producto;
select fabricante.nombre, concat(upper(substr(nombre, 1, 2))) as mayus from fabricante;
select producto.nombre, round(precio) as red from producto;
select producto.nombre, truncate(precio, 0) as trunc from producto;
select producto.codigo_fabricante from producto;
select distinct(codigo_fabricante) from producto;
select producto.nombre from producto order by producto.nombre;
select producto.nombre from producto order by producto.nombre desc;
select producto.nombre, producto.precio from producto order by producto.nombre, producto.precio desc;
select *from fabricante limit 5;
select *from fabricante limit 2 offset 3;
select producto.nombre, producto.precio from producto order by producto.precio limit 1;
select producto.nombre, producto.precio from producto order by producto.precio  desc limit 1;
select producto.nombre from producto where codigo_fabricante like 2;
select producto.nombre, producto.precio, fabricante.nombre as fabricante from producto join fabricante on producto.codigo_fabricante = fabricante.codigo;
select producto.nombre, producto.precio, fabricante.nombre as fabricante from producto join fabricante on producto.codigo_fabricante = fabricante.codigo order by fabricante.nombre;
select producto.codigo, producto.nombre, producto.codigo_fabricante, fabricante.nombre from producto join fabricante on producto.codigo_fabricante = fabricante.codigo;
select producto.nombre, producto.precio, fabricante.nombre as fabricante from producto join fabricante on producto.codigo_fabricante = fabricante.codigo order by producto.precio limit 1;
select producto.nombre, producto.precio, fabricante.nombre as fabricante from producto join fabricante on producto.codigo_fabricante = fabricante.codigo order by producto.precio desc limit 1;
select producto.nombre, fabricante.nombre from producto join fabricante on producto.codigo_fabricante = fabricante.codigo where fabricante.nombre like 'lenovo';
select producto.nombre, fabricante.nombre from producto join fabricante on producto.codigo_fabricante = fabricante.codigo where fabricante.nombre like 'crucial' and producto.precio > 200;
select producto.nombre from producto join fabricante on producto.codigo_fabricante = fabricante.codigo where fabricante.nombre = 'asus' or fabricante.nombre = 'hewlett-packard' or fabricante.nombre = 'seagate';
select producto.nombre from producto join fabricante on producto.codigo_fabricante = fabricante.codigo where fabricante.nombre in ('asus', 'hewlett-packard', 'seagate');
select producto.nombre, producto.precio from producto join fabricante on producto.codigo_fabricante = fabricante.codigo where fabricante.nombre like '%e';
select producto.nombre, producto.precio from producto join fabricante on producto.codigo_fabricante = fabricante.codigo where fabricante.nombre like '%w%';
select producto.nombre, producto.precio from producto join fabricante on producto.codigo_fabricante = fabricante.codigo where producto.precio >= 180 order by producto.precio, producto.nombre;
select fabricante.codigo, fabricante.nombre as fabricante from fabricante join producto on producto.codigo_fabricante = fabricante.codigo where producto.nombre is not null;
select fabricante.nombre as fabricante, producto.nombre as producto, producto.precio from fabricante left join producto on producto.codigo_fabricante = fabricante.codigo;
select fabricante.nombre as fabricante from fabricante left join producto on producto.codigo_fabricante = fabricante.codigo where producto.nombre is null;
select producto.nombre from producto where codigo_fabricante = (select codigo from fabricante where nombre = 'lenovo');
select producto.nombre from producto where producto.precio = (select max(producto.precio) from producto where producto.codigo_fabricante = (select fabricante.codigo from fabricante where nombre = 'lenovo'));
select producto.nombre from producto join fabricante on producto.codigo_fabricante = fabricante.codigo where fabricante.nombre ='lenovo' and producto.precio = (select max(producto.precio) from producto where producto.codigo_fabricante = fabricante.codigo);
select producto.nombre from producto join fabricante on producto.codigo_fabricante = fabricante.codigo where fabricante.nombre ='Hewlett-Packard' and producto.precio = (select min(producto.precio) from producto where producto.codigo_fabricante = fabricante.codigo);
select producto.nombre from producto where producto.precio >= (select max(producto.precio) from producto where producto.codigo_fabricante = (select fabricante.codigo from fabricante where nombre = 'lenovo'));
select producto.nombre from producto join (select producto.codigo_fabricante, avg(producto.precio) as precio_medio from producto group by producto.codigo_fabricante) as p_media on producto.codigo_fabricante = p_media.codigo_fabricante where p_media.codigo_fabricante = (select fabricante.codigo from fabricante where fabricante.nombre = 'asus') and producto.precio > p_media.precio_medio;